### ISSUE TITLE
추상클래스 서브클래스에 상속

### ISSUE THREAD

**Issue by wonyeong91** [ProjectInTheClass/ThirstyTraveler#2]
# 추상 클래스 - 서브클래스에 상속 
# 이에 따른 개별 커스텀셀만들기 ——> 메인 지도화면에서 아이콘 탭 했을때 뜨는 페이지 및 즐겨찾기 상세 페이지 동시에 해결!

**Comment by lunaticaug** [comment]
UITableViewController를 종류별로 따로 만들기
 UIFactoryTableViewController
 UIBrewery
 UIDraft
